# This file now only declares the build environment.
# The actual build logic is deferred to setup.py.
[build-system]
requires = [
    "setuptools>=61.0",
    "cython>=0.29",
    "numpy>=1.19" 
]
build-backend = "setuptools.build_meta"
